name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install flake8
        pip install -r requirements.txt || true

    - name: Lint the code
      run: flake8 .

    - name: Run unit tests
      run: |
        echo "Running dummy test..."
        python -c "assert 1 + 1 == 2"

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: yourdockerhubusername/webapp:latest

    - name: Deploy to remote server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 165.232.169.243
        username: root
        password: zfHWGGP6apAknzFl
        script: |
          docker pull yourdockerhubusername/webapp:latest
          docker stop webapp || true && docker rm webapp || true
          docker run -d --name webapp -p 80:80 yourdockerhubusername/webapp:latest
